version: '3.4'

services:
  app:
    image: ${DOCKER_REGISTRY-}app
    build:
      context: .
      dockerfile: project_euler/Dockerfile
    env_file:
     - euler.env

  apptests:
    image: ${DOCKER_REGISTRY-}apptests
    build:
      context: .
      dockerfile: Dockerfile.test

