FROM microsoft/dotnet:2.1-runtime AS base
WORKDIR /app

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY appTests/appTests.csproj appTests/
COPY project_euler/app.csproj project_euler/
RUN dotnet restore appTests/appTests.csproj
COPY . .
WORKDIR /src/appTests
RUN dotnet build appTests.csproj -c Release -o /tests

FROM build AS publish
RUN dotnet publish appTests.csproj -c Release -o /tests

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "appTests.dll"]
