version: '3.4'

services:
  app:
    image: ${DOCKER_REGISTRY-}app
    build:
      context: .
      dockerfile: project_euler/app/Dockerfile

  apptests:
    image: ${DOCKER_REGISTRY-}apptests
    build:
      context: .
      dockerfile: appTests/Dockerfile

